Repository zopefoundation/Zope, pull requests merged in 2018-11, with the labels that each got.

#318 [Products/SiteAccess] handle wildcard on rewrite url
  CHANGES.rst
  src/Products/SiteAccess/VirtualHostMonster.py
  src/Products/SiteAccess/tests/testVirtualHostMonster.py
Labels: documentation, enhancement

#398 Add security declarations to SimpleItem's FTP methods.
  CHANGES.rst
  src/OFS/DTMLMethod.py
  src/OFS/Image.py
  src/OFS/SimpleItem.py
  src/Products/PageTemplates/ZopePageTemplate.py
Labels: enhancement

#405 Update expire date on expireCookie function
  src/ZPublisher/HTTPResponse.py
  src/ZPublisher/tests/testHTTPResponse.py
Labels: do not merge
