Repository zopefoundation/Zope, pull requests merged in 2018-10, with the labels that each got.

#328 Do all DOM modifications directly on the complete callback.
  src/zmi/styles/resources/zmi_base.js
Labels: bug

#320 Fix XML Page template files in Python 3
  CHANGES.rst
  src/Products/PageTemplates/PageTemplateFile.py
  src/Products/PageTemplates/tests/testZopePageTemplate.py
  src/Products/PageTemplates/tests/test_ptfile.py
  src/Products/PageTemplates/tests/utf8.xml
  src/Products/PageTemplates/utils.py
Labels: bug

#329 added documentation about zope4 ZMI template updating
  docs/ZMI.rst
Labels: documentation

#336 Fix handling of broken objects in ZMI
  src/OFS/ObjectManager.py
  src/OFS/tests/testSorting.py
  src/OFS/zpt/main.zpt
Labels: bug

#334 Support for installing zope via pipenv #272
  .gitignore
  README.rst
  constraints.txt
  docs/INSTALL-pipenv.txt
  docs/INSTALL-virtualenv.rst
  requirements-full.txt
  util.py
Labels: documentation

#338 Use system locale if no locale is set in config
  docs/operation.rst
  src/Zope2/Startup/starter.py
  src/Zope2/Startup/wsgischema.xml
  src/Zope2/utilities/skel/etc/wsgi.conf.in
Labels: documentation, enhancement

#344 Restore support for ordered folders in ZMI
  CHANGES.rst
  src/OFS/ObjectManager.py
  src/OFS/tests/testSorting.py
  src/OFS/zpt/main.zpt
  src/zmi/styles/resources/zmi_base.css
Labels: enhancement

#348 Fix #308: default-zpublisher-encoding breaks rendering
  CHANGES.rst
  src/Zope2/Startup/datatypes.py
  src/Zope2/Startup/tests/test_schema.py
Labels: bug

#351 Use a constraints file for virtualenv install
  constraints.txt
  docs/INSTALL-virtualenv.rst
  util.py
Labels: documentation

#337 Run scripts/debug console
  CHANGES.rst
  docs/operation.rst
  setup.py
  src/Zope2/utilities/tests/__init__.py
  src/Zope2/utilities/tests/test_zconsole.py
  src/Zope2/utilities/zconsole.py
Labels: enhancement

#349 Fix edge case, if no databases are available for dropdown menu.
  CHANGES.rst
  buildout.cfg
  setup.py
  src/App/dtml/menu.dtml
  src/App/tests/test_ApplicationManager.py
Labels: bug

#340 Fix HTTPResponse.setBody when the publisher returns a tuple
  CHANGES.rst
  src/ZPublisher/HTTPResponse.py
  src/ZPublisher/tests/testHTTPResponse.py
Labels: bug

#335 Add a configuration to run zope including some optional Products.
  zope-ecosystem.cfg
Labels: enhancement

#364 Remove bootstrap.py
  CHANGES.rst
  bootstrap.py
  docs/INSTALL-buildout.rst
  versions.cfg
Labels: enhancement

#359 Update Interface/Component documentation for Python 3
  docs/zdgbook/ComponentsAndInterfaces.rst
Labels: documentation

#380 Fix handling of non-ASCII characters in URLs.
  CHANGES.rst
  src/ZPublisher/WSGIPublisher.py
  src/ZPublisher/tests/test_WSGIPublisher.py
Labels: bug

#370 Install the `ipaddress` package only on Python 2.7.
  CHANGES.rst
  setup.py
  tox.ini
Labels: enhancement

#386 Update dependencies to newest versions.
  CHANGES.rst
  buildout.cfg
  constraints.txt
  requirements-full.txt
  setup.py
  src/Zope2/utilities/tests/test_zconsole.py
  versions-prod.cfg
  versions.cfg
Labels: enhancement

#394 Get rid again of test extra introduced in #386.
  buildout.cfg
  constraints.txt
  requirements-full.txt
  setup.py
  src/OFS/tests/event.txt
  versions-prod.cfg
  versions.cfg
Labels: enhancement
