Repository zopefoundation/Zope, pull requests merged in 2019-06, with the labels that each got.

#640 Document request parameter handling
  CHANGES.rst
  docs/zdgbook/ObjectPublishing.rst
  src/ZPublisher/HTTPRequest.py
Labels: documentation

#653 Pin Paste, too as it is used in zope.ini.
  CHANGES.rst
  constraints.txt
  requirements-full.txt
  versions-prod.cfg
Labels: bug

#643 Port whitelist creation from zope.browserpage
  constraints.txt
  requirements-full.txt
  setup.py
  src/Products/Five/browser/metaconfigure.py
  src/Products/Five/browser/tests/pages.py
  src/Products/Five/browser/tests/pages.zcml
  src/Products/Five/browser/tests/test_pages.py
  versions-prod.cfg
Labels: RELEASE BLOCK

#657 Fix broken ZMI when using non-root deployments.
  CHANGES.rst
  src/App/dtml/copyright.dtml
  src/App/dtml/manage.dtml
  src/App/dtml/manage_page_header.dtml
  src/App/dtml/menu.dtml
Labels: bug
