Repository zopefoundation/Zope, pull requests merged in 2019-05, with the labels that each got.

#572 Resurrect the Interfaces ZMI tab
  CHANGES.rst
  setup.cfg
  src/OFS/SimpleItem.py
  src/Products/Five/utilities/browser/__init__.py
  src/Products/Five/utilities/browser/configure.zcml
  src/Products/Five/utilities/browser/edit_markers.pt
  src/Products/Five/utilities/browser/manage_interfaces.pt
  src/Products/Five/utilities/browser/marker.py
  src/Products/Five/utilities/browser/tests/__init__.py
  src/Products/Five/utilities/browser/tests/test_marker.py
  src/Products/Five/utilities/configure.zcml
  src/Shared/DC/Scripts/Bindings.py
Labels: enhancement

#563 Add setting to disable registered error views for debugging in WSGI setups
  .gitignore
  CHANGES.rst
  docs/wsgi.rst
  src/ZPublisher/WSGIPublisher.py
  src/ZPublisher/tests/test_WSGIPublisher.py
  src/Zope2/Startup/run.py
  src/Zope2/Startup/serve.py
  src/Zope2/Startup/starter.py
  src/Zope2/Startup/wsgischema.xml
  src/Zope2/utilities/skel/etc/wsgi.conf.in
Labels: enhancement

#586 Do not quote `@` on redirect.
  src/ZPublisher/HTTPResponse.py
  src/ZPublisher/tests/testHTTPResponse.py
Labels: RELEASE BLOCK, bug, feedback required

#595 Add conversion rule for DTMLMethod content
  src/OFS/__init__.py
Labels: enhancement

#599 Add a flag for suppressing object events during file import
  CHANGES.rst
  src/OFS/ObjectManager.py
  src/OFS/dtml/importExport.dtml
Labels: enhancement

#597 Change generated WSGI confinguation names
  CHANGES.rst
  docs/INSTALL.rst
  docs/operation.rst
  docs/zope4/migration/zodb.rst
  docs/zopebook/AdvZPT.rst
  src/Products/PageTemplates/unicodeconflictresolver.py
  src/Zope2/Startup/tests/test_schema.py
  src/Zope2/utilities/finder.py
  src/Zope2/utilities/skel/etc/zope.conf.in
  src/Zope2/utilities/skel/etc/zope.ini.in
Labels: documentation, enhancement

#598 Prevent the creation of object IDs that look like views
  CHANGES.rst
  src/OFS/ObjectManager.py
  src/OFS/tests/testObjectManager.py
Labels: bug

#590 - Add a configuration flag to show bookmarkable URLs in the ZMI
  CHANGES.rst
  src/App/dtml/manage_page_footer.dtml
  src/OFS/ObjectManager.py
  src/OFS/tests/testObjectManager.py
  src/Zope2/Startup/wsgischema.xml
  src/Zope2/utilities/skel/etc/zope.conf.in
Labels: enhancement

#607 Update to latest releases of dependencies.
  constraints.txt
  requirements-full.txt
  versions-prod.cfg
  versions.cfg
Labels: enhancement

#608 Update docs section Migrating ZODB to reflect current state.
  CHANGES.rst
  docs/zope4/migration/zodb.rst
Labels: documentation, enhancement

#628 Some ZDG book rephrase and polish
  docs/zdgbook/GettingStarted.rst
Labels: documentation

#627 Resurrect ZODB packing from the ZMI
  CHANGES.rst
  docs/zopebook/MaintainingZope.rst
  src/App/ApplicationManager.py
  src/App/dtml/dbMain.dtml
  src/App/tests/test_ApplicationManager.py
Labels: bug

#644 Simplify linting configuration and lint docs, too.
  docs/zdgbook/examples/Poll.py
  docs/zdgbook/examples/PollImplementation.py
  docs/zdgbook/examples/PollProduct.py
  tox.ini
Labels: enhancement
