Repository zopefoundation/Zope, pull requests merged in 2019-11, with the labels that each got.

#725 Fix ``__getattr__`` signature in ``UnauthorizedBinding``
  CHANGES.rst
  src/Shared/DC/Scripts/Bindings.py
Labels: bug

#733 ZMI: permission table compressed for safari
  src/OFS/dtml/properties.dtml
  src/zmi/styles/resources/zmi_base.css
  src/zmi/styles/resources/zmi_base.js
Labels: enhancement

#736 Fix broken deprecated import when ZServer is not installed
  CHANGES.rst
  src/OFS/interfaces.py
Labels: bug

#735 Add missing Paste dependency.
  CHANGES.rst
  buildout.cfg
  docs/INSTALL.rst
  setup.py
Labels: bug

#738 Updated Zope documentation sources for Zope 5
  CHANGES.rst
  docs/INSTALL.rst
  docs/conf.py
  docs/index.rst
  docs/migrations/index.rst
  docs/migrations/zope4/code.rst
  docs/migrations/zope4/content.rst
  docs/migrations/zope4/index.rst
  docs/migrations/zope4/removed.rst
  docs/migrations/zope4/zodb.rst
  docs/news.rst
  docs/operation.rst
  docs/wsgi.rst
  docs/zope4/index.rst
  setup.py
Labels: documentation
