Repository zopefoundation/Zope, pull requests merged in 2019-02, with the labels that each got.

#465 Fix faulty ZMI links due to missing URL-quoting
  CHANGES.rst
  src/OFS/ObjectManager.py
  src/OFS/tests/testObjectManager.py
  src/OFS/zpt/main.zpt
Labels: bug

#473 - Make sure conflicts are always retried and not masked by exception views
  CHANGES.rst
  src/ZPublisher/WSGIPublisher.py
  src/ZPublisher/tests/test_WSGIPublisher.py
Labels: bug

#477 Add preliminary support for Python 3.8.
  .travis.yml
  CHANGES.rst
  buildout.cfg
  setup.py
  src/OFS/tests/testObjectManager.py
  tox.ini
  versions-prod.cfg
Labels: enhancement

#483 Update dependencies to newest versions.
  .travis.yml
  CHANGES.rst
  buildout.cfg
  constraints.txt
  requirements-full.txt
  versions-prod.cfg
  versions.cfg
Labels: enhancement

#471 Prevent overlapping description in medium sized mobile views
  CHANGES.rst
  src/zmi/styles/resources/zmi_base.css
Labels: bug, feedback required

#466 Fix display of ZMI breadcrumbs with non-ASCII path elements
  CHANGES.rst
  src/App/dtml/manage_navbar.dtml
  src/OFS/DTMLMethod.py
Labels: bug

#496 Updated ACE editor JS-lib using markdown mode for editing DTML
  src/OFS/dtml/documentEdit.dtml
  src/zmi/styles/resources/ace.ajax.org/ace.js
  src/zmi/styles/resources/ace.ajax.org/mode-css.js
  src/zmi/styles/resources/ace.ajax.org/mode-html.js
  src/zmi/styles/resources/ace.ajax.org/mode-javascript.js
  src/zmi/styles/resources/ace.ajax.org/mode-less.js
  src/zmi/styles/resources/ace.ajax.org/mode-markdown.js
  src/zmi/styles/resources/ace.ajax.org/mode-python.js
  src/zmi/styles/resources/ace.ajax.org/mode-sql.js
  src/zmi/styles/resources/ace.ajax.org/mode-text.js
  src/zmi/styles/resources/ace.ajax.org/mode-xml.js
  src/zmi/styles/resources/ace.ajax.org/theme-chrome.js
  src/zmi/styles/resources/ace.ajax.org/theme-clouds.js
  src/zmi/styles/resources/ace.ajax.org/theme-eclipse.js
  src/zmi/styles/resources/ace.ajax.org/theme-mono_industrial.js
  src/zmi/styles/resources/ace.ajax.org/worker-css.js
  src/zmi/styles/resources/ace.ajax.org/worker-html.js
  src/zmi/styles/resources/ace.ajax.org/worker-javascript.js
  src/zmi/styles/resources/ace.ajax.org/worker-json.js
  src/zmi/styles/resources/ace.ajax.org/worker-xml.js
  src/zmi/styles/resources/zmi_base.js
Labels: enhancement

#497 Fix error when not selecting a file for upload in Files and Images
  CHANGES.rst
  src/OFS/Image.py
  src/OFS/tests/testFileAndImage.py
Labels: bug

#504 Make sure the WSGI Response object respects lock semantics
  CHANGES.rst
  src/ZPublisher/HTTPResponse.py
  src/ZPublisher/tests/test_WSGIPublisher.py
Labels: bug

#503 Fix subscript access on Page Template `macros` attribute
  CHANGES.rst
  src/Products/PageTemplates/engine.py
  src/Products/PageTemplates/tests/macros.pt
  src/Products/PageTemplates/tests/test_engine.py
Labels: bug

#501 ZMI-add does not recognize absolute urls #490
  src/App/dtml/manage_navbar.dtml
  src/App/dtml/manage_page_footer.dtml
  src/zmi/styles/resources/zmi_base.js
Labels: feedback required

#515 Provide additional links on PyPI with ``project_urls`` in ``setup.py``
  CHANGES.rst
  setup.py
Labels: documentation

#512 Issue #511: remove double quoting in `ZPublisher.HTTPRequest.search_t…
  CHANGES.rst
  src/ZPublisher/HTTPRequest.py
  src/ZPublisher/tests/testHTTPRequest.py
Labels: bug
