Repository zopefoundation/Zope, pull requests merged in 2023-09, with the labels that each got.

#1151 Tighten down the ZMI frame source logic to only allow site-local sources
  CHANGES.rst
  setup.py
  src/App/dtml/manage.dtml
  src/OFS/Application.py
  src/OFS/tests/testApplication.py
Labels: bug

#1146 Added Image Info for SVG files
  CHANGES.rst
  src/OFS/Image.py
Labels: enhancement

#1159 Fix version pins for Python 3.7 and 3.8.
  .github/workflows/tests.yml
  .meta.toml
  CHANGES.rst
  buildout.cfg
  constraints.txt
  requirements-full.txt
  tox.ini
  util.py
  versions-prod.cfg
  versions.cfg
Labels: enhancement

#1163 Fix RTD build.
  .readthedocs.yaml
Labels: documentation

#1157 SVG-File: avoid attr error on missing dimensions
  src/OFS/Image.py
Labels: bug
